version: '3.8'

services:
  grafana:
    image: grafana_custom:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./bin:/app/bin
      - ./public:/app/public
      - ./conf:/app/conf
    working_dir: /app
    command: ["/app/bin/grafana-server", "server", "--homepath=/app"]

